version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: platform
      ME_CONFIG_BASICAUTH_PASSWORD: platform
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
